export const siteConfig = {
  name: "本然农场",
  tagline: "回归自然，品味本真",
  
  hero: {
    title: "本然农场",
    subtitle: "城市边缘的田园牧歌 · 采摘烧烤亲子乐园",
    rating: 4.8,
    reviewCount: 395,
    pricePerPerson: 142,
    tags: ["服务:4.7", "环境:4.8", "划算:4.7"],
    comment: "宋庄商圈 休闲园区 第2名",
    address: "内军庄村与徐辛路交叉口西160米（内军庄村委会西400米）",
    distance: "距您13.3km,驾车需要约25分钟",
  },

  deals: [
    {
      id: 1,
      title: "农场门票含采摘",
      price: 104,
      originalPrice: 109,
      discount: "9.6折",
      soldCount: "年售600+",
      timeLeft: "4小时后新人恢复",
      image: "ticket",
      badge: "抢购",
    },
    {
      id: 2,
      title: "多彩小番茄3斤采摘",
      price: 65,
      originalPrice: 99,
      discount: "6.6折",
      soldCount: "年售100+",
      timeLeft: "7小时后新人恢复",
      image: "tomato",
      badge: "抢购",
    },
    {
      id: 3,
      title: "红颜草莓采摘2斤家居券",
      price: 85,
      originalPrice: 160,
      discount: "5.3折",
      soldCount: "年售70+",
      timeLeft: "6小时后新人恢复",
      image: "strawberry",
      badge: "抢购",
    },
    {
      id: 4,
      title: "【本然农场】香香的刺黄瓜采摘3斤家居券",
      price: 41,
      originalPrice: 99,
      discount: "4.1折",
      soldCount: "年售70+",
      timeLeft: "1小时后新人恢复",
      image: "cucumber",
      badge: "抢购",
    },
    {
      id: 5,
      title: "【本然农场】农场现捡土鸡蛋10枚",
      price: 30,
      originalPrice: 50,
      discount: "6.0折",
      soldCount: "年售41",
      timeLeft: "",
      image: "egg",
      badge: "抢购",
    },
    {
      id: 6,
      title: "刺黄瓜采摘5斤券",
      price: 65,
      originalPrice: 90,
      discount: "7.2折",
      soldCount: "年售11",
      timeLeft: "2小时后新人恢复",
      image: "cucumber2",
      badge: "抢购",
    },
  ],

  recommendations: [
    { name: "北京新星靓医美(三里屯...)", rating: null, category: "医学美容", distance: "距商户5.5km" },
    { name: "新声线少儿口才(亦...", rating: null, category: null, distance: null },
    { name: "U.baby 婴儿·亲子...", rating: null, category: null, distance: null },
  ],

  nav: [
    { label: "首页", href: "#hero" },
    { label: "团购优惠", href: "#deals" },
    { label: "位置信息", href: "#location" },
    { label: "关于我们", href: "#about" },
  ],
};
